import type { Linter } from 'eslint'
import { isProduction } from '../lib/common.js'

export const eslintRules: Linter.RulesRecord = {
  'arrow-body-style': 'off',
  complexity: ['error'],
  curly: 'error',
  'func-style': ['error', 'declaration'],
  'max-depth': ['error', 4],
  'max-lines': ['error', { max: 1000, skipBlankLines: true, skipComments: true }],
  'max-lines-per-function': ['error', { max: 500, skipBlankLines: true, skipComments: true }],
  'max-params': 'error',
  'no-console': [isProduction ? 'error' : 'warn', { allow: ['info', 'table', 'assert', 'warn', 'error', 'trace'] }],
  'no-debugger': isProduction ? 'error' : 'warn',
  'no-dupe-class-members': 'off',
  'no-else-return': ['error', { allowElseIf: false }],
  'no-extra-semi': 'off',
  'no-lonely-if': 'error',
  'no-mixed-spaces-and-tabs': 'off',
  'no-multi-assign': 'error',
  'no-negated-condition': 'error',
  'no-implicit-coercion': 'error',
  'no-invalid-this': 'error',
  'no-plusplus': 'error',
  'no-promise-executor-return': 'error',
  'no-useless-concat': 'error',
  'operator-assignment': 'error',
  'prefer-exponentiation-operator': 'error',
  'no-restricted-syntax': ['error', { selector: 'TSEnumDeclaration', message: "Don't declare enums" }],
  'no-undef': 'off',
  'no-unused-expressions': [
    'error',
    { allowShortCircuit: true, allowTaggedTemplates: true, allowTernary: true, enforceForJSX: true },
  ],
  'no-use-before-define': 'off',
  'no-var': 'error',
  'object-shorthand': 'error',
  'prefer-arrow-callback': 'off',
  'prefer-destructuring': [
    'error',
    { AssignmentExpression: { array: false, object: false }, VariableDeclarator: { array: false, object: true } },
    { enforceForRenamedProperties: false },
  ],
  'prefer-object-spread': 'error',
  'prefer-rest-params': 'error',
  'prefer-template': 'error',
  radix: 'error',
  'require-await': 'error',
  'sort-imports': ['error', { ignoreDeclarationSort: true }],
  // 'sort-keys': 'error',
  'accessor-pairs': ['error', { setWithoutGet: true, enforceForClassMembers: true }],
  'array-callback-return': ['error', { allowImplicit: false, checkForEach: false }],
  camelcase: ['error', { allow: ['^UNSAFE_'], properties: 'never', ignoreGlobals: true }],
  'default-case-last': 'error',
  'dot-notation': ['error', { allowKeywords: true }],
  eqeqeq: ['error', 'always', { null: 'ignore' }],
  'new-cap': ['error', { newIsCap: true, capIsNew: false, properties: true }],
  'no-array-constructor': 'error',
  'no-caller': 'error',
  'no-constant-condition': ['error', { checkLoops: false }],
  'no-empty': ['error', { allowEmptyCatch: true }],
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-implied-eval': 'error',
  'no-iterator': 'error',
  'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
  'no-lone-blocks': 'error',
  'no-multi-str': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-object-constructor': 'error',
  'no-octal-escape': 'error',
  'no-proto': 'error',
  'no-redeclare': ['error', { builtinGlobals: false }],
  'no-return-assign': ['error', 'except-parens'],
  'no-self-assign': ['error', { props: true }],
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-template-curly-in-string': 'error',
  'no-throw-literal': 'error',
  'no-undef-init': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': ['error', { defaultAssignment: false }],
  'no-unreachable-loop': 'error',
  'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none', ignoreRestSiblings: true, vars: 'all' }],
  'no-useless-call': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-constructor': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-void': 'error',
  'one-var': ['error', { initialized: 'never' }],
  'prefer-const': ['error', { destructuring: 'all' }],
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
  'symbol-description': 'error',
  'unicode-bom': ['error', 'never'],
  'use-isnan': ['error', { enforceForSwitchCase: true, enforceForIndexOf: true }],
  'valid-typeof': ['error', { requireStringLiterals: true }],
  yoda: ['error', 'never'],
}
