import { Linter } from 'eslint'
import type { FlatConfigRules } from '../../../types/eslint.js'

const eslintMajorVersion = Number.parseInt(Linter.version, 10)

export const nonCompatibleRules: FlatConfigRules =
  eslintMajorVersion > 8
    ? {
        '@next/next/no-duplicate-head': 'off',
        'compat/compat': 'off',
        'import/first': 'off',
        'import/newline-after-import': 'off',
        'promise/no-callback-in-promise': 'off',
        'promise/no-multiple-resolved': 'off',
        'promise/no-nesting': 'off',
        'promise/no-promise-in-callback': 'off',
        'promise/no-return-wrap': 'off',
        'promise/prefer-await-to-then': 'off',
        'react/display-name': 'off',
        'react/function-component-definition': 'off',
        'react/hook-use-state': 'off',
        'react/jsx-no-undef': 'off',
        'react/jsx-uses-vars': 'off',
        'react/no-arrow-function-lifecycle': 'off',
        'react/no-direct-mutation-state': 'off',
        'react/no-multi-comp': 'off',
        'react/no-string-refs': 'off',
        'react/no-this-in-sfc': 'off',
        'react/no-typos': 'off',
        'react/no-unstable-nested-components': 'off',
        'react/prop-types': 'off',
        'react/require-render-return': 'off',
        'react/sort-comp': 'off',
        'security/detect-child-process': 'off',
        'sonarjs/no-empty-collection': 'off',
        'sonarjs/no-extra-arguments': 'off',
        'sonarjs/no-gratuitous-expressions': 'off',
        'sonarjs/no-one-iteration-loop': 'off',
        'sonarjs/no-redundant-jump': 'off',
        'sonarjs/no-unused-collection': 'off',
        'sonarjs/no-use-of-empty-return-value': 'off',
        'sonarjs/prefer-immediate-return': 'off',
        'vuejs-accessibility/alt-text': 'off',
        'vuejs-accessibility/anchor-has-content': 'off',
        'vuejs-accessibility/aria-props': 'off',
        'vuejs-accessibility/aria-role': 'off',
        'vuejs-accessibility/aria-unsupported-elements': 'off',
        'vuejs-accessibility/click-events-have-key-events': 'off',
        'vuejs-accessibility/form-control-has-label': 'off',
        'vuejs-accessibility/heading-has-content': 'off',
        'vuejs-accessibility/iframe-has-title': 'off',
        'vuejs-accessibility/interactive-supports-focus': 'off',
        'vuejs-accessibility/label-has-for': 'off',
        'vuejs-accessibility/media-has-caption': 'off',
        'vuejs-accessibility/mouse-events-have-key-events': 'off',
        'vuejs-accessibility/no-access-key': 'off',
        'vuejs-accessibility/no-autofocus': 'off',
        'vuejs-accessibility/no-distracting-elements': 'off',
        'vuejs-accessibility/no-redundant-roles': 'off',
        'vuejs-accessibility/no-static-element-interactions': 'off',
        'vuejs-accessibility/role-has-required-aria-props': 'off',
        'vuejs-accessibility/tabindex-no-positive': 'off',
      }
    : {}
